# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('telephone', models.CharField(max_length=11)),
                ('expiration', models.DateTimeField(null=True, verbose_name='到期时间')),
                ('balance', models.CharField(default='', max_length=20, verbose_name='余额')),
                ('dayNum', models.CharField(default='', max_length=10, verbose_name='剩余时间')),
                ('whetherExpiration', models.CharField(default='', max_length=3, verbose_name='是否到期')),
                ('wealth', models.CharField(default='', max_length=20, verbose_name='累计充值')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_fixed', models.CharField(default='否', max_length=10, verbose_name='是否固定座位')),
                ('is_active', models.CharField(default=1, max_length=1, verbose_name='是否处于激活状态')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
