# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='卡名称')),
                ('money', models.CharField(max_length=6, verbose_name='卡金额')),
                ('gaveMoney', models.CharField(max_length=6, verbose_name='赠送金额')),
                ('frequency', models.CharField(max_length=6, verbose_name='卡次数')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('mode', models.TextField(max_length=150)),
                ('is_active', models.CharField(default=1, max_length=1, verbose_name='是否处于激活状态')),
            ],
            options={
                'db_table': 'commodity_info',
            },
        ),
        migrations.CreateModel(
            name='UserCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.UserInfo')),
            ],
            options={
                'db_table': 'user_commodity',
            },
        ),
    ]
